### ISSUE TITLE
Issue when using spongeforge-1.12.2-2838-7.1.7-RC3876

### ISSUE THREAD

**Issue by MaxSaleh** [DosMike/WarCraft-MineCraft#4]
SO basically when you jump or try to fly in creative it forces you to the ground.

**Comment by DosMike** [comment]
please attach plugin, sponge and server versions when creating bug reports. 
I can only assume that you've no yet downloaded the fix for [my toolbox](https://github.com/DosMike/MikesToolBox-Sponge-/releases)
