### ISSUE TITLE
Problem with abilities command

### ISSUE THREAD

**Issue by Shamang1** [DosMike/WarCraft-MineCraft#6]
Hello I've got a problem with this plugin i can run any abilities like /ability1 or /ultimate  but nothing is happening ! For example the ability2 of the Orc is supposed to throw slime but nothing.

I do have MikesToolBox and i'm in 1.12.2 spongeforge-1.12.2-2838-7.1.7-RC3844 and my forge is in 1.12.2-14.23.5.2825-universal. I didn't touch to the default config and i took recommanded version of WarCraft MC and MikeToolBox.

Then nothing is happening on my consol server it's just saying "... run the command /ability1".
I tried to run the command in all dimensions with all permissions etc , how can I fix this ?

Could you help me ? I don't know if the source problem comes from my mods or plugins.

It's a list of my mods/plugins : 

-worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar
-wildnature-1.2.jar
-WarCraft-0.5.2 .jar
-DamageIndicatorsMod-3.5.1.jar
-aether_continuation-1.12.2-v1.2.3.jar
-aether_legacy-1.12.2-v1.4.4.jar
-backpack-3.0.2-1.12.2.jar
-betteranimalsplus-1.12.2-7.1.1.jar
-Bloodmoon-MC1.12.2-1.5.3.jar
-CarrotShop-1.19-S7.1-MC1.12.2.jar
CraftTweaker2-1.12-4.1.19.jar
ElecCore-1.12.2-1.9.452.jar
enchcontrol-1.12.2-1.1.5-0.jar
flexiblelogin-0.17.4.jar
galaxite-1.0.2-mc1.12.x.jar
harvestersnight-1.12.2-1.1.0.jar
Huds-1.12.2-1.0.3.jar
infernalisplayerheads-0.2.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.15.0.268.jar
JobsLite-7.1.0-1.8.1.jar
JustAFewFish-1.7_for_1.12.jar
llibrary-1.7.19-1.12.2.jar
LuckPerms-Sponge-4.4.31.jar
LuckPermsMVdWHook.jar
MagicArsenal-MC1.12_ver1.2.5.jar
materialchanger1.0.3-1.12.2.jar
MikesToolBox-1.0.1.jar
MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar
MobsPropertiesRandomness-2.3.1-mc1.12.x.jar
modtweaker-4.0.17.jar
mowziesmobs-1.5.4.jar
MTLib-3.0.6.jar
multimob-1.0.5.jar
mutatedmobs-1.0.6.jar
NoPortal-1.1.0.jar
Nucleus-1.12.2-S7.1-MC1.12.2-plugin.jar
OptiFine_1.12.2_HD_U_E3.jar
PayDay-1.4.0.jar
PlaceholderAPI-2.10.4.jar
primitivemobs-1.2.3a.jar
projectcore-7.2.0-0.3.0.jar
projectportals-7.2.0-0.15.2.jar
projectworlds-7.2.0-0.13.1.jar
RankUpper-4.0.4-b20-Universal.jar
Rex%27s-Additional-Structures-1.12.x-.jar
RoguelikeDungeons-Mod-1.12.2.jar
simplecore-1.12.2-1.7.3.4.jar
simpleores-1.12.2-1.11.2.0.jar
SkinChanger.jar
Souls-1.12.2-3.0.0.jar
spongeforge-1.12.2-2838-7.1.7-RC3844.jar
TotalEconomy-1.8.1.jar
ToughAsNails-1.12.2-3.1.0.139-universal.jar
TrackMe.jar
-UniverseGuard-2.17.jar
-WarCraft-0.5.2.jar

Thx for trying to help me ! Ask me if u want more details on specific mod/plugin/config or just proof.

**Comment by DosMike** [comment]
Looks like profile.getIfActive(player) always returned false... :<
I'll push a patch shortly

**Comment by DosMike** [comment]
Btw, your Version of Mike's ToolBox is outdated (version 1.2.2 is the most recent)
